# Project information
site_name: Azure IoT Hub Demo
site_description: IoT application on Azure to connect a RaspberryPi to IoT Hub. 
site_author: Sander van Dorsten
site_url: https://sandervandorsten.github.io/azure-iothub-demo/


# Repository
repo_name: sandervandorsten/azure-iothub-demo
repo_url: https://github.com/sandervandorsten/azure-iothub-demo

# Copyright
copyright: Copyright &copy; 2020 Sander van Dorsten

# Configuration
theme:
    name: material
    language: en
    palette:
      scheme: preference
      primary: green
      accent: orange
    font:
      text: Roboto
      code: Roboto Mono
    features:
      - instant

    
nav:
  - Azure IoT Hub Demo: index.md
  - Deploying Infrastructure: deploy.md
  - Installing Services: 
    - "IoT Hub: Registering A Device": Installation/iot-hub.md
    - "Stream Analytics: Starting the analysis job": Installation/stream-analytics.md
    - "Azure Function: Deploying a function": Installation/function.md
  - Usage:
      - Using a Simulated RaspberryPi: Usage/simulated-pi.md
      - Using a Real RaspberryPi: Usage/raspberry-pi.md
  - External links: links.md

# Extras
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/sandervandorsten
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/in/sandervandorsten

# Extensions
markdown_extensions:
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.keys
    - pymdownx.smartsymbols
    - codehilite:
        guess_lang: False
        use_pygments: True
        noclasses: True
        linenums: True
        pygments_style: monokai
    - toc:
        permalink: true